MACOSX_DEPLOYMENT_TARGET:  # [linux]
  - 10.9                   # [linux]

version:
  - 22.1.0
  - 21.1.8
  - 20.1.8
  - 19.1.7

# everything below is zipped
cross_target_platform:
  - osx-64
  - osx-arm64
macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
meson_cpu_family:
  - x86_64
  - aarch64
uname_kernel_release:
  - 13.4.0
  - 20.0.0
uname_machine:
  - x86_64
  - arm64

zip_keys:
  -
    - cross_target_platform
    - macos_machine
    - meson_cpu_family
    - uname_kernel_release
    - uname_machine
