{% set version = "9.0.1" %}

package:
  name: clang-compiler-activation
  version: {{ version }}

# Not strictly needed but enables automatic updates from the bot
source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/clang-{{ version }}.src.tar.xz
  sha256: 5778512b2e065c204010f88777d44b95250671103e434f9dc7363ab2e3804253

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - libcxx {{ version }}

outputs:
  - name: clang_{{ cross_target_platform }}
    script: install-clang.sh
    requirements:
      - clang {{ version }}
      - llvm-tools {{ version }}
      - cctools
      - ld64
      # This brings in libraries for linux too. Split this again?
      - compiler-rt {{ version }}
      - compiler-rt_{{ cross_target_platform }} {{ version }}
    test:
      commands:
        - {{ macos_machine }}-clang --version    # [osx]

  - name: clangxx_{{ cross_target_platform }}
    script: install-clangxx.sh
    requirements:
      host:
        - clangxx {{ version }}
        - libcxx {{ version }}  # [osx]
        - {{ pin_subpackage('clang_' ~ cross_target_platform, min_pin='x.x.x.x.x.x.x.x', max_pin='x.x.x.x.x.x.x.x') }}
      run:
        - clangxx {{ version }}
        # This is not needed in Linux for cross-compiling in a conda-build env, but is needed outside
        - libcxx >={{ version }}
        - {{ pin_subpackage('clang_' ~ cross_target_platform, min_pin='x.x.x.x.x.x.x.x', max_pin='x.x.x.x.x.x.x.x') }}
    # Since transitive run_exports are not currently possible
    # (here I would like the run dependency on clangxx to pull in the run_exports from it).
    run_exports:
      strong:
        - libcxx >={{ version }}
    test:
      commands:
        - {{ macos_machine }}-clang++ --version    # [osx]

  - name: clang_bootstrap_{{ cross_target_platform }}
    requirements:
      host:
        - clangxx {{ version }}
        - libcxx {{ version }}
        - cctools                                  # [osx]
        - ld64                                     # [osx]
        - {{ pin_subpackage('clang_' ~ cross_target_platform, exact=True) }}
        - {{ pin_subpackage('clangxx_' ~ cross_target_platform, exact=True) }}
    build:
      always_include_files:
        - bin/
        - etc/
        - include/
        - lib/
        - libexec/
        - share/
      skip: True  # [not osx]
    test:
      commands:
        - {{ macos_machine }}-clang --version      # [osx]
        - {{ macos_machine }}-clang++ --version    # [osx]
    about:
      home: https://llvm.org
      license: Apache-2.0
      license_family: Apache
      license_file: LLVM_LICENSE.txt
      summary: 'clang compiler components in one package for bootstrapping clang'

about:
  home: http://github.com/AnacondaRecipes/aggregate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'clang compilers for conda-build 3'

extra:
  recipe-maintainers:
    - isuruf
    - mingwandroid
