conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
channel_priority: flexible
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
# due to https://github.com/conda/conda-build/issues/4787
remote_ci_setup:
- conda-forge-ci-setup=3
- py-lief<0.12
test: native_and_emulated
