conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
channel_priority: flexible
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
